/* Create a class with a main( ) that throws an object of class Exception inside a try block. Give the constructor for Exception a 
String argument. Catch the exception inside a catch clause and print the String argument. Add a finally clause and print a message
 to prove you were there.*/

/*class main{
	public static void main(String[] args) {
		try{
			throw new Exception("Exception called");
		}
		catch(Exception e){
			System.out.println(e.toString());
		}

		finally{
			System.out.println("In finally");
		}

	}
}*/


/* Define an object reference and initialize it to null. 
Try to call a method through this reference. Now wrap the code in a try-catch clause to catch the exception.*/

